#!/usr/bin/python
#
# get_deps.py
# $Id$
#
# Copyright 2008 by Alexander Lehmann <lehmanna@in.tum.de>
#
# This file is part of annot8.
# 
# annot8 is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
# 
# annot8 is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.  See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with
# annot8.  If not, see <http://www.gnu.org/licenses/>.
#


import os, sys, re


OTOOL_PATH="/usr/bin/otool"


# Recursively finds all dependencies of the given executable.
# Returns a list of those dependencies.
def getDeps(execFileName):
    # Look for libraries but exclude those provided directly
    # by OS X (they should exist on any system by default).
    negExpr = re.compile("^\s*(/usr/lib|/System).*$")
    libExpr = re.compile("^\s+(/[^\s]+lib[^\s]+).*$")

    deps = { execFileName : 1 }
    while True:
        newDeps = deps.copy()
        for fileName in deps.keys():
            pipe = os.popen("%s -L %s" % (OTOOL_PATH, fileName))
            for line in pipe.readlines():
                tmp = libExpr.match(line)
                if tmp and (not negExpr.match(line)):
                    newDeps[tmp.group(1)] = 1
            pipe.close()

        if deps == newDeps:
            break
        deps.update(newDeps)

    deps.pop(execFileName)
    return deps.keys()
                

if __name__ == "__main__":
    if sys.platform != "darwin":
        print "This script is intended for use on Mac OS X only."
        sys.exit(1)

    if len(sys.argv) != 2:
        print "Syntax: python get_deps.py <executable>"
        sys.exit(1)

    for dep in getDeps(sys.argv[1]):
        print dep
