#############################################################################
# Makefile for building: build/debug/annot8
# Generated by qmake (2.01a) (Qt 4.4.0) on: Mo Sep 8 12:11:37 2008
# Project:  annot8.pro
# Template: app
# Command: /usr/local/Trolltech/current/bin/qmake -macx -o Makefile annot8.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DDEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.4.0/mkspecs/macx-g++ -I. -I/usr/local/Trolltech/Qt-4.4.0/include/QtCore -I/usr/local/Trolltech/Qt-4.4.0/include/QtCore -I/usr/local/Trolltech/Qt-4.4.0/include/QtGui -I/usr/local/Trolltech/Qt-4.4.0/include/QtGui -I/usr/local/Trolltech/Qt-4.4.0/include/QtSql -I/usr/local/Trolltech/Qt-4.4.0/include/QtSql -I/usr/local/Trolltech/Qt-4.4.0/include -Ibuild/debug -Ibuild/debug
LINK          = g++
LFLAGS        = -headerpad_max_install_names
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.4.0/lib -lQtSql_debug -L/sw/lib -L/usr/local/Trolltech/Qt-4.4.0/lib -lpgport -lpam -lssl -lcrypto -lkrb5 -lreadline -lpq -lQtGui_debug -framework Carbon -framework AppKit -lQtCore_debug -lz -lm -framework ApplicationServices
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/local/Trolltech/current/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.3

####### Output directory

OBJECTS_DIR   = build/debug/

####### Files

SOURCES       = main.cpp \
		DBController.cpp 
OBJECTS       = build/debug/main.o \
		build/debug/DBController.o
DIST          = /usr/local/Trolltech/Qt-4.4.0/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/common/mac.conf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/common/mac-g++.conf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/mac/default_pre.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/mac/default_post.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/mac/objective_c.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/mac/rez.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/mac/sdk.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/lex.prf \
		annot8.pro
QMAKE_TARGET  = annot8
DESTDIR       = build/debug/
TARGET        = build/debug/annot8

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) build/debug/ || $(MKDIR) build/debug/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: annot8.pro  /usr/local/Trolltech/Qt-4.4.0/mkspecs/macx-g++/qmake.conf /usr/local/Trolltech/Qt-4.4.0/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/common/mac.conf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/common/mac-g++.conf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/mac/default_pre.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/mac/default_post.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/mac/objective_c.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/mac/rez.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/mac/sdk.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.4.0/lib/libQtSql_debug.prl \
		/usr/local/Trolltech/Qt-4.4.0/lib/libQtCore_debug.prl \
		/usr/local/Trolltech/Qt-4.4.0/lib/libQtGui_debug.prl
	$(QMAKE) -macx -o Makefile annot8.pro
/usr/local/Trolltech/Qt-4.4.0/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/common/mac.conf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/common/mac-g++.conf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/mac/default_pre.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/debug.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/mac/default_post.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/mac/objective_c.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/mac/rez.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/mac/sdk.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.4.0/lib/libQtSql_debug.prl:
/usr/local/Trolltech/Qt-4.4.0/lib/libQtCore_debug.prl:
/usr/local/Trolltech/Qt-4.4.0/lib/libQtGui_debug.prl:
qmake:  FORCE
	@$(QMAKE) -macx -o Makefile annot8.pro

dist: 
	@$(CHK_DIR_EXISTS) build/debug/annot81.0.0 || $(MKDIR) build/debug/annot81.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/debug/annot81.0.0/ && $(COPY_FILE) --parents DBController.h build/debug/annot81.0.0/ && $(COPY_FILE) --parents main.cpp DBController.cpp build/debug/annot81.0.0/ && (cd `dirname build/debug/annot81.0.0` && $(TAR) annot81.0.0.tar annot81.0.0 && $(COMPRESS) annot81.0.0.tar) && $(MOVE) `dirname build/debug/annot81.0.0`/annot81.0.0.tar.gz . && $(DEL_FILE) -r build/debug/annot81.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

build/debug/main.o: main.cpp DBController.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/main.o main.cpp

build/debug/DBController.o: DBController.cpp DBController.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/DBController.o DBController.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

